In [477]:
import pandas as pd
import numpy as np

In [478]:
df_deliveries = pd.read_csv('CSV/deliveries.csv')
df_matches = pd.read_csv('CSV/matches.csv')

In [479]:
df_deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [480]:
df_deliveries.isna().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [481]:
df_deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [482]:
df_deliveries.shape

(260920, 17)

In [483]:
df_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [484]:
df_matches.isna().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [485]:
df_matches.shape

(1095, 20)

In [486]:
df_matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [487]:
df_matches['team1'].value_counts()

team1
Royal Challengers Bangalore    135
Chennai Super Kings            128
Mumbai Indians                 123
Kolkata Knight Riders          121
Rajasthan Royals               101
Kings XI Punjab                 92
Sunrisers Hyderabad             86
Delhi Daredevils                85
Delhi Capitals                  41
Deccan Chargers                 39
Punjab Kings                    31
Lucknow Super Giants            23
Pune Warriors                   23
Gujarat Titans                  21
Gujarat Lions                   16
Royal Challengers Bengaluru      9
Kochi Tuskers Kerala             7
Rising Pune Supergiant           7
Rising Pune Supergiants          7
Name: count, dtype: int64

In [488]:
teams = [
    'Sunrisers Hyderabad', 'Mumbai Indians', 'Royal Challengers Bangaluru',
    'Kolkata Knight Riders', 'Punjab Kings', 'Chennai Super Kings',
    'Rajasthan Royals', 'Delhi Capitals', 'Gujarat Titans', 'Lucknow Super Giants'
]

In [489]:
df_matches['team1'] = df_matches['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
df_matches['team2'] = df_matches['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

df_matches['team1'] = df_matches['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
df_matches['team2'] = df_matches['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

df_matches['team1'] = df_matches['team1'].str.replace('Kings XI Punjab','Punjab Kings')
df_matches['team2'] = df_matches['team2'].str.replace('Kings XI Punjab','Punjab Kings')

df_matches['team1'] = df_matches['team1'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')
df_matches['team2'] = df_matches['team2'].str.replace('Royal Challengers Bangalore','Royal Challengers Bengaluru')

In [490]:
df_matches = df_matches[df_matches['team1'].isin(teams)]
df_matches = df_matches[df_matches['team2'].isin(teams)]

In [491]:
df_matches = df_matches[df_matches['method'].isna()]

In [492]:
df_matches.groupby('city')['venue'].unique()

city
Abu Dhabi         [Sheikh Zayed Stadium, Zayed Cricket Stadium, ...
Ahmedabad         [Sardar Patel Stadium, Motera, Narendra Modi S...
Bangalore                                   [M Chinnaswamy Stadium]
Bloemfontein                                      [OUTsurance Oval]
Cape Town                                                [Newlands]
Centurion                                         [SuperSport Park]
Chandigarh        [Punjab Cricket Association Stadium, Mohali, P...
Chennai           [MA Chidambaram Stadium, Chepauk, MA Chidambar...
Cuttack                                          [Barabati Stadium]
Delhi             [Feroz Shah Kotla, Arun Jaitley Stadium, Arun ...
Dharamsala        [Himachal Pradesh Cricket Association Stadium,...
Dubai                         [Dubai International Cricket Stadium]
Durban                                                  [Kingsmead]
East London                                          [Buffalo Park]
Guwahati                      [Barsapara Cricket Stadium, Guwahati]
Hyderabad         [Rajiv Gandhi International Stadium, Uppal, Ra...
Indore                                     [Holkar Cricket Stadium]
Jaipur            [Sawai Mansingh Stadium, Sawai Mansingh Stadiu...
Johannesburg                                [New Wanderers Stadium]
Kimberley                                   [De Beers Diamond Oval]
Kolkata                       [Eden Gardens, Eden Gardens, Kolkata]
Lucknow           [Bharat Ratna Shri Atal Bihari Vajpayee Ekana ...
Mohali            [Maharaja Yadavindra Singh International Crick...
Mumbai            [Dr DY Patil Sports Academy, Wankhede Stadium,...
Nagpur               [Vidarbha Cricket Association Stadium, Jamtha]
Navi Mumbai                    [Dr DY Patil Sports Academy, Mumbai]
Port Elizabeth                                   [St George's Park]
Pune              [Subrata Roy Sahara Stadium, Maharashtra Crick...
Raipur            [Shaheed Veer Narayan Singh International Stad...
Ranchi                         [JSCA International Stadium Complex]
Sharjah                                   [Sharjah Cricket Stadium]
Visakhapatnam     [Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket S...
Name: venue, dtype: object

In [493]:
df_matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Punjab Kings,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Delhi Capitals,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,1426305,2024,Mumbai,2024-05-17,League,N Pooran,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Mumbai Indians,Mumbai Indians,field,Lucknow Super Giants,runs,18.0,215.0,20.0,N,NaN,Navdeep Singh,R Pandit
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [494]:
df_deliveries.head(1)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN

In [495]:
df_matches['venue_clean'] = (
    df_matches['venue']
    .str.strip()
    .str.lower()
    .str.split(",").str[0]
)

In [496]:
df_matches['venue_clean'].value_counts()

venue_clean
wankhede stadium                                                91
eden gardens                                                    71
ma chidambaram stadium                                          68
rajiv gandhi international stadium                              58
sawai mansingh stadium                                          43
feroz shah kotla                                                43
dubai international cricket stadium                             34
punjab cricket association stadium                              27
arun jaitley stadium                                            26
dr dy patil sports academy                                      24
brabourne stadium                                               23
sheikh zayed stadium                                            23
sharjah cricket stadium                                         20
punjab cricket association is bindra stadium                    19
narendra modi stadium                                           18
maharashtra cricket association stadium                         18
bharat ratna shri atal bihari vajpayee ekana cricket stadium    13
sardar patel stadium                                            11
dr. y.s. rajasekhara reddy aca-vdca cricket stadium             11
himachal pradesh cricket association stadium                    11
kingsmead                                                       10
supersport park                                                  8
zayed cricket stadium                                            6
barabati stadium                                                 6
maharaja yadavindra singh international cricket stadium          5
holkar cricket stadium                                           4
newlands                                                         4
st george's park                                                 4
new wanderers stadium                                            4
shaheed veer narayan singh international stadium                 4
m chinnaswamy stadium                                            3
jsca international stadium complex                               3
de beers diamond oval                                            3
buffalo park                                                     3
barsapara cricket stadium                                        3
outsurance oval                                                  2
vidarbha cricket association stadium                             2
subrata roy sahara stadium                                       1
Name: count, dtype: int64

In [497]:
venue_mapping = {
    # Delhi
    "feroz shah kotla": "arun jaitley stadium",
    "arun jaitley stadium": "arun jaitley stadium",

    # Ahmedabad
    "sardar patel stadium": "narendra modi stadium",
    "motera": "narendra modi stadium",
    "narendra modi stadium": "narendra modi stadium",

    # Mohali
    "punjab cricket association stadium": "punjab cricket association is bindra stadium",
    "punjab cricket association is bindra stadium": "punjab cricket association is bindra stadium",

    # Pune
    "subrata roy sahara stadium": "maharashtra cricket association stadium",
    "maharashtra cricket association stadium": "maharashtra cricket association stadium",

    # Abu Dhabi
    "sheikh zayed stadium": "zayed cricket stadium",
    "zayed cricket stadium": "zayed cricket stadium",

    # Chennai
    "ma chidambaram stadium": "ma chidambaram stadium",

    # Mumbai
    "wankhede stadium": "wankhede stadium",
    "brabourne stadium": "brabourne stadium",
    "dr dy patil sports academy": "dr dy patil sports academy",

    # Hyderabad
    "rajiv gandhi international stadium": "rajiv gandhi international stadium",

    # Visakhapatnam
    "dr. y.s. rajasekhara reddy aca-vdca cricket stadium": "dr. y.s. rajasekhara reddy aca-vdca cricket stadium",

    # Jaipur
    "sawai mansingh stadium": "sawai mansingh stadium",

    # Nagpur
    "vidarbha cricket association stadium": "vidarbha cricket association stadium",

    # Lucknow
    "bharat ratna shri atal bihari vajpayee ekana cricket stadium": "bharat ratna shri atal bihari vajpayee ekana cricket stadium",

    # Ranchi
    "jsca international stadium complex": "jsca international stadium complex",

    # Raipur
    "shaheed veer narayan singh international stadium": "shaheed veer narayan singh international stadium",

    # Indore
    "holkar cricket stadium": "holkar cricket stadium",

    # Bangalore
    "m chinnaswamy stadium": "m chinnaswamy stadium",

    # Kolkata
    "eden gardens": "eden gardens",

    # International (South Africa / UAE)
    "newlands": "newlands",
    "kingsmead": "kingsmead",
    "supersport park": "supersport park",
    "st george's park": "st george's park",
    "new wanderers stadium": "new wanderers stadium",
    "buffalo park": "buffalo park",
    "outsurance oval": "outsurance oval",
    "de beers diamond oval": "de beers diamond oval",
    "barsapara cricket stadium": "barsapara cricket stadium",
    "sharjah cricket stadium": "sharjah cricket stadium",
    "dubai international cricket stadium": "dubai international cricket stadium",
    "maharaja yadavindra singh international cricket stadium": "maharaja yadavindra singh international cricket stadium",
}

In [498]:
df_matches['venue_clean'] = (
    df_matches['venue_clean']
    .str.strip().str.lower()
    .replace(venue_mapping)
)

In [499]:
df_matches.drop('venue', axis=1,inplace=True)
df_matches.rename(columns={'venue_clean':'venue'},inplace=True)

In [500]:
df_matches.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'target_runs', 'target_overs', 'super_over', 'method',
       'umpire1', 'umpire2', 'venue'],
      dtype='object')

In [501]:
df_matches.groupby('city')['venue'].unique()

city
Abu Dhabi                                   [zayed cricket stadium]
Ahmedabad                                   [narendra modi stadium]
Bangalore                                   [m chinnaswamy stadium]
Bloemfontein                                      [outsurance oval]
Cape Town                                                [newlands]
Centurion                                         [supersport park]
Chandigarh           [punjab cricket association is bindra stadium]
Chennai                                    [ma chidambaram stadium]
Cuttack                                          [barabati stadium]
Delhi                                        [arun jaitley stadium]
Dharamsala           [himachal pradesh cricket association stadium]
Dubai                         [dubai international cricket stadium]
Durban                                                  [kingsmead]
East London                                          [buffalo park]
Guwahati                                [barsapara cricket stadium]
Hyderabad                      [rajiv gandhi international stadium]
Indore                                     [holkar cricket stadium]
Jaipur                                     [sawai mansingh stadium]
Johannesburg                                [new wanderers stadium]
Kimberley                                   [de beers diamond oval]
Kolkata                                              [eden gardens]
Lucknow           [bharat ratna shri atal bihari vajpayee ekana ...
Mohali            [maharaja yadavindra singh international crick...
Mumbai            [dr dy patil sports academy, wankhede stadium,...
Nagpur                       [vidarbha cricket association stadium]
Navi Mumbai                            [dr dy patil sports academy]
Port Elizabeth                                   [st george's park]
Pune                      [maharashtra cricket association stadium]
Raipur            [shaheed veer narayan singh international stad...
Ranchi                         [jsca international stadium complex]
Sharjah                                   [sharjah cricket stadium]
Visakhapatnam     [dr. y.s. rajasekhara reddy aca-vdca cricket s...
Name: venue, dtype: object

In [502]:
df_matches = df_matches[['id','venue','winner','target_runs']]

In [503]:
df_matches.rename(columns={'id' : 'match_id'},inplace=True)

C:\Users\shres\AppData\Local\Temp\ipykernel_9976\3260332357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_matches.rename(columns={'id' : 'match_id'},inplace=True)

In [504]:
delivery = df_matches.merge(df_deliveries, on='match_id')

In [505]:
delivery = delivery[delivery['inning'] == 2]

In [506]:
delivery.shape

(84825, 20)

In [507]:
delivery['current_score'] = delivery.groupby('match_id')['total_runs'].cumsum()

In [508]:
delivery['runs_left'] =  delivery['target_runs'] - delivery['current_score']

In [509]:
delivery['balls_left'] =  120 - (delivery['over'] * 6 + delivery['ball'])

In [510]:
delivery

,match_id,venue,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
124,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,1,K Goel,...,0,4,NaN,0,NaN,NaN,NaN,4,237.0,119
125,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,2,K Goel,...,0,0,NaN,0,NaN,NaN,NaN,4,237.0,118
126,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,3,K Goel,...,0,0,NaN,0,NaN,NaN,NaN,4,237.0,117
127,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,4,K Goel,...,0,1,NaN,0,NaN,NaN,NaN,5,236.0,116
128,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,5,JR Hopes,...,0,0,NaN,0,NaN,NaN,NaN,5,236.0,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175121,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,110,4.0,61
175122,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,111,3.0,60
175123,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,112,2.0,59
175124,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,0,1,NaN,0,NaN,NaN,NaN,113,1.0,58
175125,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,0,1,NaN,0,NaN,NaN,NaN,114,0.0,57

In [511]:
wickets = delivery.groupby('match_id')['is_wicket'].cumsum()
delivery['wickets_left'] = 10 - wickets

In [512]:
delivery['crr'] = delivery['current_score'] * 6 / (120- delivery['balls_left'])

In [513]:
delivery['rrr'] = delivery['runs_left'] * 6 / delivery['balls_left']

In [514]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

In [515]:
delivery['result'] = delivery.apply(result,axis=1)

In [516]:
delivery

,match_id,venue,winner,target_runs,inning,batting_team,bowling_team,over,ball,batter,...,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left,crr,rrr,result
124,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,1,K Goel,...,NaN,NaN,NaN,4,237.0,119,10,24.000000,11.949580,0
125,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,2,K Goel,...,NaN,NaN,NaN,4,237.0,118,10,12.000000,12.050847,0
126,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,3,K Goel,...,NaN,NaN,NaN,4,237.0,117,10,8.000000,12.153846,0
127,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,4,K Goel,...,NaN,NaN,NaN,5,236.0,116,10,7.500000,12.206897,0
128,335983,punjab cricket association is bindra stadium,Chennai Super Kings,241.0,2,Kings XI Punjab,Chennai Super Kings,0,5,JR Hopes,...,NaN,NaN,NaN,5,236.0,115,10,6.000000,12.313043,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175121,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,...,NaN,NaN,NaN,110,4.0,61,8,11.186441,0.393443,1
175122,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,...,NaN,NaN,NaN,111,3.0,60,8,11.100000,0.300000,1
175123,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,...,NaN,NaN,NaN,112,2.0,59,8,11.016393,0.203390,1
175124,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,...,NaN,NaN,NaN,113,1.0,58,8,10.935484,0.103448,1
175125,1426312,ma chidambaram stadium,Kolkata Knight Riders,114.0,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,...,NaN,NaN,NaN,114,0.0,57,8,10.857143,0.000000,1

In [517]:
final_df = delivery[['match_id','batting_team','bowling_team','venue','runs_left','balls_left','wickets_left','target_runs','crr','rrr','result']]

In [518]:
final_df = final_df[final_df['balls_left'] != 0]

In [519]:
final_df.dropna(subset=['rrr'],inplace=True)

In [520]:
final_df.isna().sum()

match_id        0
batting_team    0
bowling_team    0
venue           0
runs_left       0
balls_left      0
wickets_left    0
target_runs     0
crr             0
rrr             0
result          0
dtype: int64

In [521]:
final_df['venue'].value_counts()

venue
wankhede stadium                                                10571
eden gardens                                                     8155
arun jaitley stadium                                             8052
ma chidambaram stadium                                           8014
rajiv gandhi international stadium                               6677
punjab cricket association is bindra stadium                     5361
sawai mansingh stadium                                           4955
dubai international cricket stadium                              4023
zayed cricket stadium                                            3374
narendra modi stadium                                            3315
dr dy patil sports academy                                       2785
brabourne stadium                                                2750
sharjah cricket stadium                                          2259
maharashtra cricket association stadium                          2223
bharat ratna shri atal bihari vajpayee ekana cricket stadium     1417
himachal pradesh cricket association stadium                     1308
dr. y.s. rajasekhara reddy aca-vdca cricket stadium              1270
kingsmead                                                        1232
supersport park                                                   924
barabati stadium                                                  711
maharaja yadavindra singh international cricket stadium           612
new wanderers stadium                                             474
st george's park                                                  462
newlands                                                          455
holkar cricket stadium                                            454
shaheed veer narayan singh international stadium                  453
barsapara cricket stadium                                         365
de beers diamond oval                                             358
jsca international stadium complex                                347
m chinnaswamy stadium                                             339
buffalo park                                                      334
outsurance oval                                                   248
vidarbha cricket association stadium                              246
Name: count, dtype: int64

In [522]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [523]:
unique_matches = final_df['match_id'].unique()
train_matches, test_matches = train_test_split(
    unique_matches, test_size=0.2, random_state=2
)

In [524]:
train_matches.shape

(580,)

In [525]:
test_matches.shape

(146,)

In [526]:
train_data = final_df[final_df['match_id'].isin(train_matches)]
test_data = final_df[final_df['match_id'].isin(test_matches)]

In [527]:
train_data['match_id'].value_counts().sort_values()

match_id
336021      38
1082626     49
1254093     53
1426312     67
1304078     69
          ...
1426294    130
1426288    131
1370350    131
1304076    131
1359480    135
Name: count, Length: 580, dtype: int64

In [528]:
test_data['match_id'].value_counts().sort_values()

match_id
1426270     55
1426295     60
548307      68
1082635     83
1178413     94
          ...
1254069    128
419142     128
1304053    129
829777     130
829811     133
Name: count, Length: 146, dtype: int64

In [529]:
train_data = train_data.sample(frac = 1, random_state=42).reset_index(drop=True)
test_data = test_data.sample(frac = 1, random_state=42).reset_index(drop=True)

In [530]:
X_train = train_data.drop(columns=['result','match_id'])
y_train = train_data['result']

X_test = test_data.drop(columns=['result','match_id'])
y_test = test_data['result']

In [531]:
trf = ColumnTransformer(
    transformers=[
        ('trf', OneHotEncoder(sparse_output=False, drop='first'), ['batting_team', 'bowling_team', 'venue'])
    ], remainder='passthrough'
)

In [532]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [533]:
X_train['venue'].value_counts()

venue
wankhede stadium                                                7721
arun jaitley stadium                                            6801
eden gardens                                                    6573
ma chidambaram stadium                                          5744
rajiv gandhi international stadium                              5224
punjab cricket association is bindra stadium                    4770
sawai mansingh stadium                                          3668
dubai international cricket stadium                             3429
zayed cricket stadium                                           2895
narendra modi stadium                                           2813
dr dy patil sports academy                                      2203
brabourne stadium                                               1994
maharashtra cricket association stadium                         1850
sharjah cricket stadium                                         1680
himachal pradesh cricket association stadium                    1308
dr. y.s. rajasekhara reddy aca-vdca cricket stadium             1167
bharat ratna shri atal bihari vajpayee ekana cricket stadium    1101
kingsmead                                                        987
supersport park                                                  820
maharaja yadavindra singh international cricket stadium          612
new wanderers stadium                                            474
barabati stadium                                                 474
newlands                                                         455
holkar cricket stadium                                           454
barsapara cricket stadium                                        365
de beers diamond oval                                            358
st george's park                                                 340
vidarbha cricket association stadium                             246
jsca international stadium complex                               224
shaheed veer narayan singh international stadium                 220
buffalo park                                                     217
m chinnaswamy stadium                                            214
outsurance oval                                                  122
Name: count, dtype: int64

In [534]:
X_test['venue'].value_counts()

venue
wankhede stadium                                                2850
ma chidambaram stadium                                          2270
eden gardens                                                    1582
rajiv gandhi international stadium                              1453
sawai mansingh stadium                                          1287
arun jaitley stadium                                            1251
brabourne stadium                                                756
dubai international cricket stadium                              594
punjab cricket association is bindra stadium                     591
dr dy patil sports academy                                       582
sharjah cricket stadium                                          579
narendra modi stadium                                            502
zayed cricket stadium                                            479
maharashtra cricket association stadium                          373
bharat ratna shri atal bihari vajpayee ekana cricket stadium     316
kingsmead                                                        245
barabati stadium                                                 237
shaheed veer narayan singh international stadium                 233
outsurance oval                                                  126
m chinnaswamy stadium                                            125
jsca international stadium complex                               123
st george's park                                                 122
buffalo park                                                     117
supersport park                                                  104
dr. y.s. rajasekhara reddy aca-vdca cricket stadium              103
Name: count, dtype: int64

In [535]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team',
                                                   'venue'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [536]:
scores = cross_val_score(pipe,X_train,y_train,cv = 10, scoring = 'accuracy' )
print(f'CV Accuracy scores: {scores}')
print(f'mean : {scores.mean()}')

CV Accuracy scores: [0.81904339 0.82126462 0.81400859 0.82183057 0.82153436 0.81901659
 0.82508886 0.81768365 0.8264218  0.82834716]
mean : 0.8214239585811608

In [537]:
y_pred = pipe.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, y_pred))


print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("Classification Report:\n", classification_report(y_test, y_pred))

Test Accuracy: 0.7530588235294118
Confusion Matrix:
 [[6371 2215]
 [1983 6431]]
Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.74      0.75      8586
           1       0.74      0.76      0.75      8414

    accuracy                           0.75     17000
   macro avg       0.75      0.75      0.75     17000
weighted avg       0.75      0.75      0.75     17000